sudo: required
dist: xenial
language: python
python:
  - 3.6
  - 3.7
  - 3.8

before_install:
  - sudo apt-get -yq install software-properties-common
  - sudo apt-add-repository -y multiverse
  - sudo apt-get -yq update
  - sudo apt-get -yq install automake build-essential libyaml-dev
  - pip install -r requirements.txt
  - pip install coveralls pyre-check==0.0.32
  - mkdir plugins

install:
  - python3 setup.py install

script:
  - pyre --noninteractive check
  - coverage run setup.py test

after_success: coveralls
